### ISSUE TITLE
RTK

### ISSUE THREAD

**Issue by auroralwj** [XiaoGongWei/MG_APP#32]
你好，请问一下后续有做RTK的打算吗？

**Comment by XiaoGongWei** [comment]
你好，我暂时没有做RTK打算。你可以基于这套代码做RTK，因为MG-APP里面含有很多模型和方法，省去了做RTK的成本，你只需要新建一个类（类似QPPPModel），然后把RTK流程组织起来即可。

**Comment by auroralwj** [comment]
好的，十分感谢
